import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  const data = api.recipe.getAll.useQuery();
  console.log(data, "<====data");

  return (
    <>
      <Head>
        <title>Foodie Love</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-emerald-500">
        <div className="flex items-center justify-end space-x-4 px-3 py-2">
          <Link href="/" className="text-stone-100 hover:bg-emerald-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Recipe</Link>
          <Link href="/" className="text-stone-100 hover:bg-emerald-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium ">Create</Link>
        </div>
      </nav>
      <main>
        <section className="grid lg-grid-cols-3">

        </section>
      </main>
    </>
  );
};

export default Home;
